### PR TITLE
Remove chai as dependency

### PR DESCRIPTION
**Pull request by wheresrhys**
Doesn't appear to be in use, and causes dependency problems for me upstream

### CODE REVIEW

**Comment by davidfhaines** [comment]
Unlike pg-crypt, chai has a much bigger role in msgpack-javascript. Will need to refactor message-packer and message-unpacker before dropping chai (e.g., assert.isArray | isNumber | isBelow | isBoolean, etc). How quickly do you need this?

**Comment by wheresrhys** [comment]
We've got a workaround so it's OK. I thought it wasn't in use as github search doesn't work in forked repos

**Comment by davidfhaines** [comment]
@wheresrhys just released v0.10.0 sans chai.

**Comment by wheresrhys** [comment]
great - thanks again

**Pull request closed without merging**
